AMA-428 - add checkboxes and new status -> uploading
cilt-uct/tsugi-migrate-to-brightspace pull request #15
Opened 2022-11-30 16:35 UTC by NgoniChoga

2022-12-01 11:34 UTC, npmali requested changes

2022-12-01 11:34 UTC, npmali commented on admin-home.php
> +    'conversion_test' => $LAUNCH->ltiRawParameter('conversion_test', false)
In order for the 'Test conversion' checkbox to be checked on default, add "custom_" in front of the 'conversion_test' ltiRawParameter. 

So this line should be:

`'conversion_test' => $LAUNCH->ltiRawParameter('custom_conversion_test', false)`

2022-12-01 11:34 UTC, npmali commented on templates/admin-body.html
> +                                                    Enrol site owners and support staff</label>
I think you're missing text on this label. According to the JIRA the text should be: 

`Enrol site owners and support staff in the converted site`

2022-12-01 12:56 UTC, TurRil requested changes

2022-12-01 12:56 UTC, TurRil commented on templates/admin-footer.html
> +            var conversion_test = $('#conversion_test').is(':checked') ? 'test_conversion' : 'btnAccept';
Maybe change it to:
```
var btn_type =$('#conversion_test').is(':checked') ? 'test_conversion' : 'btnAccept';
```
So it is the same as line 344.

2022-12-01 12:56 UTC, TurRil commented on templates/admin-footer.html
> +        function showError(conversion_test) {
Change `conversion_test` to `btn` to make it more descriptive (I know `a` was not really descriptive enough for this)

2022-12-01 12:56 UTC, TurRil commented on templates/admin-footer.html
> +        function submit_sites(sites, conversion_test, text, enrol) {
Change `conversion_test` to `btn`

2022-12-01 12:56 UTC, TurRil commented on templates/admin-footer.html
> +                $('#' + conversion_test).html('<i class="fa fa-cog fa-spin"></i>' + text).addClass('disabled').attr('disabled', true);
Change `conversion_test` to `btn`

2022-12-01 12:56 UTC, TurRil commented on templates/admin-footer.html
> +                        $('#' + conversion_test).html('<i class="fa fa-check"></i> Refreshing page ...');
Change `conversion_test` to `btn`

2022-12-01 12:56 UTC, TurRil commented on templates/admin-footer.html
> +                        showError(conversion_test);
Change `conversion_test` to `btn`

2022-12-01 12:56 UTC, TurRil commented on templates/admin-footer.html
> +        function doPost(conversion_test, text, enrol) {
Change `conversion_test` to `btn`

2022-12-05 09:56 UTC, TurRil approved these changes

2022-12-05 09:57 UTC, TurRil approved these changes

2022-12-05 09:57 UTC, merged