AMA-697: Add missing columns and keys to database.php
cilt-uct/tsugi-migrate-to-brightspace pull request #18
Opened 2023-04-13 08:29 UTC by npmali

2023-04-13 13:49 UTC, TurRil requested changes

2023-04-13 13:49 UTC, TurRil commented on database.php
> +    `failure_detail` VARCHAR(255) DEFAULT NULL,
There are some additional fields here that should also be added in the function`$DATABASE_UPGRADE` = function($oldversion) {` and in the array `$add_some_fields = array(`

2023-04-13 13:49 UTC, TurRil commented on database.php
> +    `failure_detail` VARCHAR(255) DEFAULT NULL,
like all of these:
```
`site_url` VARCHAR(255) DEFAULT NULL,
    `archive_log` mediumtext,
    `site_owners` mediumtext,
    `zip_size` bigint(20) unsigned DEFAULT NULL,
    `failure_type` enum('exception','expired','import-error') DEFAULT NULL,
    `failure_detail` VARCHAR(255) DEFAULT NULL,
```

2023-04-13 15:21 UTC, npmali commented on database.php
> +    `failure_detail` VARCHAR(255) DEFAULT NULL,
Added additional fields to $DATABASE_UPGRADE function

2023-04-14 11:35 UTC, TurRil approved these changes

2023-04-14 11:35 UTC, merged